version: '3.9'

services:
  # Backend - Laravel
  app:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - ./back-end:/var/www/html
      - ./back-end/storage:/var/www/html/storage
    ports:
      - "9000:9000"

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    volumes:
      - ./back-end:/var/www/html
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "8080:80"
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: laravel_db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: secret

  # Frontend - Vue.js
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: vue_frontend
    volumes:
      - ./front-end:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"

volumes:
  db_data:
