name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  back-end:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [8.2, 8.3]

    name: PHP ${{ matrix.php }}

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer

      - name: Copy .env
        run: |
          cd back-end
          php -r "file_exists('.env') || copy('.env.example', '.env');"

      # Install dependencies
      - name: Install Composer dependencies
        run: |
          cd back-end
          composer update
          composer install

      - name: Generate key
        run: |
          cd back-end
          php artisan key:generate
        
      - name: Directory Permissions
        run: |
          cd back-end
          chmod -R 777 storage bootstrap/cache
        
      - name: Create Database
        run: |
          cd back-end
          mkdir -p database
          touch database/database.sqlite
          
      - name: Execute tests (Unit and Feature tests) via Pest
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: |
          cd back-end
          php artisan migrate --seed
          composer test